/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class chen_pa_com_nativeandroid_PAJni */

#ifndef _Included_chen_pa_com_nativeandroid_PAJni
#define _Included_chen_pa_com_nativeandroid_PAJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     chen_pa_com_nativeandroid_PAJni
 * Method:    nativeGetStrFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_chen_pa_com_nativeandroid_PAJni_nativeGetStrFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     chen_pa_com_nativeandroid_PAJni
 * Method:    nativeSetJObjectValueInNative
 * Signature: (Lchen/pa/com/nativeandroid/JNISetObj;)V
 */
JNIEXPORT void JNICALL Java_chen_pa_com_nativeandroid_PAJni_nativeSetJObjectValueInNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     chen_pa_com_nativeandroid_PAJni
 * Method:    nativeRetriveJava
 * Signature: (Lchen/pa/com/nativeandroid/JNISetObj;)V
 */
JNIEXPORT void JNICALL Java_chen_pa_com_nativeandroid_PAJni_nativeRetriveJava
  (JNIEnv *, jobject, jobject);

/*
 * Class:     chen_pa_com_nativeandroid_PAJni
 * Method:    nativeParameterArray
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_chen_pa_com_nativeandroid_PAJni_nativeParameterArray
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
