/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_app_PAJni */

#ifndef _Included_com_jni_app_PAJni
#define _Included_com_jni_app_PAJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_app_PAJni
 * Method:    nativeGetStrFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_app_PAJni_nativeGetStrFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_app_PAJni
 * Method:    nativeSetJObjectValueInNative
 * Signature: (Lcom/jni/app/JNISetObj;)V
 */
JNIEXPORT void JNICALL Java_com_jni_app_PAJni_nativeSetJObjectValueInNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_jni_app_PAJni
 * Method:    nativeRetriveJava
 * Signature: (Lcom/jni/app/JNISetObj;)V
 */
JNIEXPORT void JNICALL Java_com_jni_app_PAJni_nativeRetriveJava
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_jni_app_PAJni
 * Method:    nativeParameterArray
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_jni_app_PAJni_nativeParameterArray
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
